// Package docs GENERATED BY SWAG; DO NOT EDIT
// This file was generated by swaggo/swag
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/v1/accounts": {
            "get": {
                "security": [
                    {
                        "BasicAuth": []
                    }
                ],
                "description": "Get Merchant Accounts godoc",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "MerchantAccount"
                ],
                "summary": "Get Merchant Accounts godoc",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Merchant Account ID",
                        "name": "id",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Merchant Account Code",
                        "name": "code",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Merchant Account Name",
                        "name": "name",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": " ",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": " ",
                        "name": "limit",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/rest.ResponseGetAccounts"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/rest.HTTPErrResp"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/rest.HTTPErrResp"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/rest.HTTPErrResp"
                        }
                    }
                }
            },
            "put": {
                "description": "Update Merchant Account By Id",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "MerchantAccount"
                ],
                "summary": "Update Merchant Account By Id",
                "parameters": [
                    {
                        "description": "Body Request",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/entity.UpdateMerchantAccount"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/rest.ResponseCreateAccount"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/rest.HTTPErrResp"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/rest.HTTPErrResp"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/rest.HTTPErrResp"
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "BasicAuth": [
                            ""
                        ]
                    }
                ],
                "description": "Create Merchant Account",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "MerchantAccount"
                ],
                "summary": "Create Merchant Account",
                "parameters": [
                    {
                        "description": "Body Request",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/entity.CreateAccountParam"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/rest.ResponseCreateAccount"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/rest.HTTPErrResp"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/rest.HTTPErrResp"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/rest.HTTPErrResp"
                        }
                    }
                }
            }
        },
        "/v1/accounts/members": {
            "get": {
                "description": "Get Merchant Members By Parameters",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "MerchantMember"
                ],
                "summary": "Get Merchant Members By Parameters",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Merchant Member ID",
                        "name": "id",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Merchant Account ID",
                        "name": "merchantId",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Merchant Member Email",
                        "name": "email",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Merchant Account Name",
                        "name": "name",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": " ",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": " ",
                        "name": "limit",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/rest.ResponseGetMembers"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/rest.HTTPErrResp"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/rest.HTTPErrResp"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/rest.HTTPErrResp"
                        }
                    }
                }
            },
            "put": {
                "description": "Update Merchant Member By Id",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "MerchantMember"
                ],
                "summary": "Update Merchant Member By Id",
                "parameters": [
                    {
                        "description": "Body Request",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/entity.UpdateMerchantMember"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/rest.ResponseCreateMember"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/rest.HTTPErrResp"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/rest.HTTPErrResp"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/rest.HTTPErrResp"
                        }
                    }
                }
            },
            "post": {
                "description": "Create Merchant Member",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "MerchantMember"
                ],
                "summary": "Create Merchant Member",
                "parameters": [
                    {
                        "description": "Body Request",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/entity.CreateMemberParam"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/rest.ResponseCreateMember"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/rest.HTTPErrResp"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/rest.HTTPErrResp"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/rest.HTTPErrResp"
                        }
                    }
                }
            }
        },
        "/v1/accounts/members/{member_id}": {
            "delete": {
                "description": "Delete Merchant Member By Id",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "MerchantMember"
                ],
                "summary": "Delete Merchant Member By Id",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Merchant Member ID",
                        "name": "member_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/rest.ResponseCreateAccount"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/rest.HTTPErrResp"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/rest.HTTPErrResp"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/rest.HTTPErrResp"
                        }
                    }
                }
            }
        },
        "/v1/accounts/{account_id}": {
            "delete": {
                "security": [
                    {
                        "BasicAuth": [
                            ""
                        ]
                    }
                ],
                "description": "Delete Merchant Account By Id",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "MerchantAccount"
                ],
                "summary": "Delete Merchant Account By Id",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Merchant Account ID",
                        "name": "account_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/rest.ResponseCreateAccount"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/rest.HTTPErrResp"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/rest.HTTPErrResp"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/rest.HTTPErrResp"
                        }
                    }
                }
            }
        },
        "/v1/support/pre-define-questions-for-authentication": {
            "get": {
                "description": "Get Predefine questions for authentication user",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "CustomerSupport"
                ],
                "summary": "Get Predefine questions for authentication user",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/rest.ResponseGetPredefineQuestionForAuthentication"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/rest.HTTPErrResp"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/rest.HTTPErrResp"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/rest.HTTPErrResp"
                        }
                    }
                }
            }
        },
        "/v1/support/pre-define-questions-for-business": {
            "get": {
                "description": "Get Predefine questions for user",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "CustomerSupport"
                ],
                "summary": "Get Predefine questions for user",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/rest.ResponseGetPredefineQuestionForBusiness"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/rest.HTTPErrResp"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/rest.HTTPErrResp"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/rest.HTTPErrResp"
                        }
                    }
                }
            }
        },
        "/v1/support/submit-questions-for-answer": {
            "post": {
                "description": "Submit Question for Anwser",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "CustomerSupport"
                ],
                "summary": "Submit Question for Anwser",
                "parameters": [
                    {
                        "description": "Body Request",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/entity.Question"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/rest.ResponseAnswerForQuestion"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/rest.HTTPErrResp"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/rest.HTTPErrResp"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/rest.HTTPErrResp"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "entity.Answer": {
            "type": "object",
            "properties": {
                "content": {},
                "id": {
                    "type": "string"
                }
            }
        },
        "entity.CreateAccountParam": {
            "type": "object",
            "properties": {
                "merchant_code": {
                    "type": "string",
                    "maxLength": 50,
                    "minLength": 1
                },
                "merchant_name": {
                    "type": "string",
                    "maxLength": 200,
                    "minLength": 1
                }
            }
        },
        "entity.CreateMemberParam": {
            "type": "object",
            "properties": {
                "member_email": {
                    "type": "string",
                    "maxLength": 100,
                    "minLength": 1
                },
                "member_name": {
                    "type": "string",
                    "maxLength": 200,
                    "minLength": 1
                },
                "merchant_id": {
                    "type": "integer"
                }
            }
        },
        "entity.ErrorMessage": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "string"
                },
                "message": {
                    "type": "string"
                }
            }
        },
        "entity.MerchantAccount": {
            "type": "object",
            "properties": {
                "createdAt": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "merchant_code": {
                    "type": "string"
                },
                "merchant_name": {
                    "type": "string"
                },
                "merchant_status": {
                    "type": "string"
                },
                "updatedAt": {
                    "type": "string"
                }
            }
        },
        "entity.MerchantMember": {
            "type": "object",
            "properties": {
                "createdAt": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "member_email": {
                    "type": "string"
                },
                "member_name": {
                    "type": "string"
                },
                "member_status": {
                    "type": "string"
                },
                "merchant_id": {
                    "type": "integer"
                },
                "updatedAt": {
                    "type": "string"
                }
            }
        },
        "entity.MerchantMemberData": {
            "type": "object",
            "properties": {
                "created_at": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "member_email": {
                    "type": "string"
                },
                "member_name": {
                    "type": "string"
                },
                "member_status": {
                    "type": "string"
                },
                "merchant": {
                    "$ref": "#/definitions/entity.MerchantAccount"
                },
                "updated_at": {
                    "type": "string"
                }
            }
        },
        "entity.Meta": {
            "type": "object",
            "properties": {
                "error": {
                    "$ref": "#/definitions/entity.ErrorMessage"
                },
                "path": {
                    "type": "string"
                },
                "status": {
                    "type": "string"
                },
                "status_code": {
                    "type": "integer"
                },
                "timestamp": {
                    "type": "string"
                }
            }
        },
        "entity.Pagination": {
            "type": "object",
            "properties": {
                "current_page": {
                    "type": "integer"
                },
                "cursor_end": {
                    "type": "string"
                },
                "cursor_start": {
                    "description": "TODO improve pagination using cursor",
                    "type": "string"
                },
                "sort_by": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "total_elements": {
                    "type": "integer"
                },
                "total_pages": {
                    "type": "integer"
                }
            }
        },
        "entity.Parameter": {
            "type": "object",
            "properties": {
                "isRequired": {
                    "type": "boolean"
                },
                "name": {
                    "type": "string"
                },
                "value": {
                    "type": "string"
                }
            }
        },
        "entity.Question": {
            "type": "object",
            "properties": {
                "content": {
                    "type": "string"
                },
                "function": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "parameters": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/entity.Parameter"
                    }
                },
                "questionType": {
                    "type": "string"
                },
                "topic": {
                    "type": "string"
                }
            }
        },
        "entity.QuestionForAuthentication": {
            "type": "object",
            "properties": {
                "content": {
                    "type": "string"
                },
                "field": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "isRequired": {
                    "type": "boolean"
                },
                "questionType": {
                    "type": "string"
                },
                "supportOTP": {
                    "type": "boolean"
                }
            }
        },
        "entity.UpdateMerchantAccount": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "integer"
                },
                "merchant_code": {
                    "type": "string"
                },
                "merchant_name": {
                    "type": "string"
                }
            }
        },
        "entity.UpdateMerchantMember": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "integer"
                },
                "member_email": {
                    "type": "string"
                },
                "member_name": {
                    "type": "string"
                }
            }
        },
        "rest.HTTPErrResp": {
            "type": "object",
            "properties": {
                "metadata": {
                    "$ref": "#/definitions/entity.Meta"
                }
            }
        },
        "rest.ResponseAnswerForQuestion": {
            "type": "object",
            "properties": {
                "data": {
                    "$ref": "#/definitions/entity.Answer"
                },
                "metadata": {
                    "$ref": "#/definitions/entity.Meta"
                }
            }
        },
        "rest.ResponseCreateAccount": {
            "type": "object",
            "properties": {
                "data": {
                    "$ref": "#/definitions/entity.MerchantAccount"
                },
                "metadata": {
                    "$ref": "#/definitions/entity.Meta"
                }
            }
        },
        "rest.ResponseCreateMember": {
            "type": "object",
            "properties": {
                "data": {
                    "$ref": "#/definitions/entity.MerchantMember"
                },
                "metadata": {
                    "$ref": "#/definitions/entity.Meta"
                }
            }
        },
        "rest.ResponseGetAccounts": {
            "type": "object",
            "properties": {
                "data": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/entity.MerchantAccount"
                    }
                },
                "metadata": {
                    "$ref": "#/definitions/entity.Meta"
                },
                "pagination": {
                    "$ref": "#/definitions/entity.Pagination"
                }
            }
        },
        "rest.ResponseGetMembers": {
            "type": "object",
            "properties": {
                "data": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/entity.MerchantMemberData"
                    }
                },
                "metadata": {
                    "$ref": "#/definitions/entity.Meta"
                },
                "pagination": {
                    "$ref": "#/definitions/entity.Pagination"
                }
            }
        },
        "rest.ResponseGetPredefineQuestionForAuthentication": {
            "type": "object",
            "properties": {
                "data": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/entity.QuestionForAuthentication"
                    }
                },
                "metadata": {
                    "$ref": "#/definitions/entity.Meta"
                }
            }
        },
        "rest.ResponseGetPredefineQuestionForBusiness": {
            "type": "object",
            "properties": {
                "data": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/entity.Question"
                    }
                },
                "metadata": {
                    "$ref": "#/definitions/entity.Meta"
                }
            }
        }
    },
    "securityDefinitions": {
        "BasicAuth": {
            "type": "basic"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "",
	Description:      "",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
